-- +goose Up
-- Booking operations workspace: human reference, supplier PNR, service
-- classification, sales channel, internal notes, change (reissue) requests
-- and richer passenger records.

ALTER TABLE bookings
    ADD COLUMN IF NOT EXISTS ref_no          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN IF NOT EXISTS pnr             TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS service_type    TEXT NOT NULL DEFAULT 'package',
    ADD COLUMN IF NOT EXISTS supplier_source TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS channel         TEXT NOT NULL DEFAULT 'agent',
    ADD COLUMN IF NOT EXISTS summary         TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS company_name    TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS reissue_count   INT  NOT NULL DEFAULT 0;

ALTER TABLE bookings
    ADD CONSTRAINT bookings_service_type_check
        CHECK (service_type IN ('flight','hotel','package','transfer','visa','tour')),
    ADD CONSTRAINT bookings_supplier_source_check
        CHECK (supplier_source IN ('','duffel','paximum','amadeus','sabre','saadia','nusuk','direct_contract','other')),
    ADD CONSTRAINT bookings_channel_check
        CHECK (channel IN ('b2c_web','b2b_agency','whatsapp_bot','agent')),
    ADD CONSTRAINT bookings_reissue_count_check CHECK (reissue_count >= 0);

CREATE UNIQUE INDEX IF NOT EXISTS idx_bookings_ref_no ON bookings(ref_no);
CREATE INDEX IF NOT EXISTS idx_bookings_pnr ON bookings(upper(pnr)) WHERE pnr <> '';
CREATE INDEX IF NOT EXISTS idx_bookings_hold_open ON bookings(hold_expires_at) WHERE status = 'option_hold';
CREATE INDEX IF NOT EXISTS idx_bookings_branch_channel ON bookings(branch_id, channel, service_type);
CREATE INDEX IF NOT EXISTS idx_bookings_created ON bookings(branch_id, created_at DESC);

ALTER TABLE booking_participants
    ADD COLUMN IF NOT EXISTS gender            TEXT    NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS national_id_enc   TEXT    NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS national_id_last4 TEXT    NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS health_ok         BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE booking_participants
    ADD CONSTRAINT booking_participants_gender_check CHECK (gender IN ('','male','female'));

CREATE TABLE IF NOT EXISTS booking_notes (
    id          UUID PRIMARY KEY,
    booking_id  UUID NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    author_id   UUID NOT NULL REFERENCES users(id),
    body        TEXT NOT NULL CHECK (length(body) BETWEEN 1 AND 4000),
    pinned      BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_booking_notes_booking ON booking_notes(booking_id, pinned DESC, created_at DESC);

CREATE TABLE IF NOT EXISTS booking_change_requests (
    id               UUID PRIMARY KEY,
    booking_id       UUID NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    kind             TEXT NOT NULL CHECK (kind IN ('date_change','name_change','route_change','other')),
    details          TEXT NOT NULL CHECK (length(details) BETWEEN 1 AND 2000),
    status           TEXT NOT NULL DEFAULT 'requested' CHECK (status IN ('requested','completed','rejected')),
    requested_by     UUID NOT NULL REFERENCES users(id),
    resolved_by      UUID NULL REFERENCES users(id),
    resolution_note  TEXT NOT NULL DEFAULT '',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_at      TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS idx_booking_changes_booking ON booking_change_requests(booking_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_booking_changes_open ON booking_change_requests(booking_id) WHERE status = 'requested';

-- Activity feed: events about a booking's children carry booking_id in metadata.
CREATE INDEX IF NOT EXISTS idx_audit_events_booking_ref
    ON audit_events ((metadata->>'booking_id'), created_at DESC)
    WHERE metadata ? 'booking_id';

-- +goose Down
DROP INDEX IF EXISTS idx_audit_events_booking_ref;
DROP TABLE IF EXISTS booking_change_requests;
DROP TABLE IF EXISTS booking_notes;
ALTER TABLE booking_participants
    DROP CONSTRAINT IF EXISTS booking_participants_gender_check,
    DROP COLUMN IF EXISTS health_ok,
    DROP COLUMN IF EXISTS national_id_last4,
    DROP COLUMN IF EXISTS national_id_enc,
    DROP COLUMN IF EXISTS gender;
DROP INDEX IF EXISTS idx_bookings_created;
DROP INDEX IF EXISTS idx_bookings_branch_channel;
DROP INDEX IF EXISTS idx_bookings_hold_open;
DROP INDEX IF EXISTS idx_bookings_pnr;
DROP INDEX IF EXISTS idx_bookings_ref_no;
ALTER TABLE bookings
    DROP CONSTRAINT IF EXISTS bookings_reissue_count_check,
    DROP CONSTRAINT IF EXISTS bookings_channel_check,
    DROP CONSTRAINT IF EXISTS bookings_supplier_source_check,
    DROP CONSTRAINT IF EXISTS bookings_service_type_check,
    DROP COLUMN IF EXISTS reissue_count,
    DROP COLUMN IF EXISTS company_name,
    DROP COLUMN IF EXISTS summary,
    DROP COLUMN IF EXISTS channel,
    DROP COLUMN IF EXISTS supplier_source,
    DROP COLUMN IF EXISTS service_type,
    DROP COLUMN IF EXISTS pnr,
    DROP COLUMN IF EXISTS ref_no;
